config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'posts#index', as: 'home'

  get 'about' => 'pages#about', as: 'about'

  resources :posts do
    resources :versions, only: [:destroy] do
      member do
        get :diff, to: 'versions#diff'
        patch :rollback, to: 'versions#rollback'
      end
    end
  end

  # resources :posts
end

app/models/application_record.rb
# auto-generated class
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
# Model for trainingposts. Validation also takes place here.
class Post < ApplicationRecord
  has_paper_trail
  validates :title, presence: true,
                    length: { minimum: 4 }
end

# Currently used for activating paper trail gem
class Widget < ActiveRecord::Base
  has_paper_trail
  # has_paper_trail on: [:update, :create]
end

app/controllers/application_controller.rb
# Default controller for application
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
# Controller for different pages
class PagesController < ApplicationController
  def about
    @title = 'About us'
    @content = 'Welcome to training manager. Here you can log and and
    analyze your training results'
  end
end

app/controllers/posts_controller.rb
# Controller for different actions related to training posts
class PostsController < ApplicationController
  before_action :set_post, only: %i(show edit update destroy)

  def history
    @versions = Version.find(params[:id])
  end

  def index
    @posts = Post.all
  end

  def show
    @post = Post.find(params[:id])
  end

  def new
    @post = Post.new
  end

  def create
    # render plain:params[:post].inspect
    @post = Post.new(post_params)

    if @post.save
      redirect_to edit_post_path(@post), notice: 'New post saved.'
    else
      render :new
    end
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])

    if @post.update(post_params)
      redirect_to @post
    else
      render :edit
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy

    redirect_to posts_path
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_post
    @post = Post.find(params[:id])
  end

  private def post_params
    params.require(:post).permit(:title, :body)
  end
end

app/controllers/versions_controller.rb
# Controller for managing post versions and differences
class VersionsController < ApplicationController
  before_action :set_post_and_version, only: %i(diff rollback destroy)

  def diff; end

  def rollback
    # change the current document to the specified version
    # reify gives you the object of this version
    post = @version.reify
    post.save
    redirect_to edit_post_path(post)
  end

  private

  def set_post_and_version
    @post = Post.find(params[:post_id])
    @version = @post.versions.find(params[:id])
  end
end

app/helpers/application_helper.rb
# Default helper for application
module ApplicationHelper
end

app/helpers/pages_helper.rb
# Helper for managing different pages
module PagesHelper
end

app/helpers/posts_helper.rb
# Helper for managing posts and their differences
module PostsHelper
  def diff(content1, content2)
    changes = Diffy::Diff.new(content1, content2,
                              include_plus_and_minus_in_html: true,
                              include_diff_info: true)
    changes.to_s.present? ? changes.to_s(:html).html_safe : 'No Changes'
  end
end

app/helpers/versions_helper.rb
# Helper for managing versions
module VersionsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Trainingmanager</title>
    <%= stylesheet_link_tag 'https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css' %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track'  => true %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <nav class="navbar navbar-default">
          <div class="container">
            <div class="navbar-header">
              <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
              </button>
              <a class="navbar-brand" href="#">Training manager</a>
            </div>
            <div id="navbar" class="collapse navbar-collapse">
              <ul class="nav navbar-nav">
                  <li><%= link_to "Home", home_path %></li>
              </ul>
              <ul class="nav navbar-nav navbar-middle">
                  <li><%= link_to "Create Training entry", new_post_path %></li>
              </ul>
              <ul class="nav navbar-nav navbar-right">
                  <li><%= link_to "About", about_path %></li>
              </ul>
            </div><!--/.nav-collapse -->
          </div>
        </nav>
<div class="container">
    <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<h1><%= @title %> </h1>
<p><%= @content %> </p>
<p> Training manager by Hando Laasmägi. </p>

app/views/posts/_form.html.erb
<%= form_for(@post, { role: 'form' }) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :title %><br>
    <%= f.text_field :title, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :body %><br>
    <%= f.text_area :body, class: 'form-control document-text-area' %>
  </div>
  <div class='fr'>
    <%= link_to 'Back', posts_path, class: 'btn btn-danger' %>
    <%= f.submit 'Save', class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/posts/_versions.html.erb
<table class='table'>
  <thead>
    <tr>
      <th>Index</th>
      <th>Date</th>
      <th>Author</th>
      <th>Event</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <%- @post.versions.each do |version| %>
      <tr>
        <td><%= version.index %></td>
        <td><%= version.created_at %></td>
        <td>Hando</td>
        <td><%= version.event.humanize %></td>

        <%- if version.next != nil %>
        <td><%=link_to 'Difference with current', diff_post_version_path(post, version.next)%></td>
        <td><%=link_to 'Rollback to this version', rollback_post_version_path(post, version.next), method: 'PATCH'%></td>
        <% else %>
        <td>This is the current version</td>
        <td>This is the current version</td>
        <% end %>

      </tr>
    <% end %>
  </tbody>
</table>

app/views/posts/edit.html.erb
<h1>Edit training result<h1/>

<%= form_for :post, url: post_path(@post), method: :patch do |f| %>
  <% if @post.errors.any? %>
        <% @post.errors.full_messages.each do |msg| %>
        <div class="alert alert-danger"><%= msg %></div>
        <% end %>
    <% end %>
<p>
<%= f.label :title%> <br>
<%= f.text_field(:title, {:class => 'form-control'}) %>
</p>

<p>
<%= f.label :body%> <br>
<%= f.text_area(:body, {:class => 'form-control'}) %>
</p>


<p>
<%= f.submit({:class => 'btn btn-primary'}) %>
</p>


</div>

<% end %>


<!-- <%= render 'form' %> -->

<%= render 'posts/versions', post: @post %>

app/views/posts/index.html.erb
<h1> Training manager!</h1>
<% @posts.each do |post| %>
  <div class ="well">
  <h3><%= post.title %></h3>
    <p><%= post.body %></p>
    <p>Creating time: <%= post.created_at %></p>

    <%= link_to "Read More", post_path(post), :class => 'btn
      btn-default' %>
  </div>
<% end %>

app/views/posts/new.html.erb
<h1>Add a training result<h1/>

<%= form_for :post, url: posts_path do |f| %>
  <% if @post.errors.any? %>
        <% @post.errors.full_messages.each do |msg| %>
        <div class="alert alert-danger"><%= msg %></div>
        <% end %>
    <% end %>
<p>
<%= f.label :title%> <br>
<%= f.text_field(:title, {:class => 'form-control'}) %>
</p>

<p>
<%= f.label :body%> <br>
<%= f.text_area(:body, {:class => 'form-control'}) %>
</p>

<p>
<%= f.submit({:class => 'btn btn-primary'}) %>
</p>

<% end %>



<!--<%= render 'form' %>-->

app/views/posts/show.html.erb
<h2><%=@post.title%></h2>
<p><%@post.body%></p>
<p>Post created at: <%=@post.created_at%></p>
<p>Post updated at: <%=@post.updated_at%></p>



<hr>
<%= link_to "Edit", edit_post_path(@post), :class => 'btn btn-default' %>
<%= link_to "Delete", post_path(@post),
          method: :delete,
          data:  {confirm: 'Are you sure?'},
          :class => 'btn btn-danger' %>

app/views/versions/diff.html.erb
# app/views/versions/diff.html.erb
<div class='row mt'>
  <div class='col-sm-12'>
    <h2><%= "Diff between Version #{@version.index} and Current Version" %></h2>
    <style><%= Diffy::CSS %></style>
    <div class='well diff'>
      <p>
        <strong>Name:</strong>
        <%= diff(@version.reify.title, @post.title) %>
      </p>
      <p>
        <strong>Content:</strong>
        <%= diff(@version.reify.body, @post.body) %>
      </p>
    </div>
    <p>
    <%= "On #{@version.created_at} by '#{@version.event.humanize}'." %>
    </p>
  </div>
</div>
<div class='fr'>
  <%= link_to 'Back', edit_post_path(@post), class: 'btn btn-danger' %>
<%= link_to 'Rollback', rollback_post_version_path(@post, @version), class: 'btn btn-primary', method: 'PATCH' %>
</div>